name: GraphQL API Documentation
on:
  push:
    branches:
      - "master"
    paths:
      - "server/internal/graphql/schema/schema.graphql"

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
    runs-on: ubuntu-22.04
    if: github.repository == 'meshery/meshery'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout repo 🛎️
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # v1.190.0
        with:
          ruby-version: 2.7.5
          bundler-cache: true

      - name: graphql-docs
        run: |
          cd docs
          bundle install
          bundle exec rake graphql:compile_docs

      - name: Pull changes from remote
        run: git pull origin master

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        with:
          file_pattern: docs/
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "[Docs] Generated documentation for GraphQL API"
          branch: master
